
import SideBar from '@/components/SideBar'
import '../styles/globals.css'
import { getServerSession } from 'next-auth'
import { SessionProvider } from '@/components/SessionProvider'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import Login from '@/components/Login'
import ClientProvider from '@/components/ClientProvider'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions)
  console.log(session)
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>

          {!session ? (<Login />) : (
            <div className='flex'>
              {/* sidebar */}
              <div className='bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]'>

                <SideBar />
              </div>

              {/* client-provider */}
              <ClientProvider />
              <div className='bg-[#1111] flex-1'>
                {children}
              </div>
            </div>)}
        </SessionProvider>
      </body>
    </html>
  )
}
